### ISSUE TITLE
Filter ‘bj_lazy_load_html’ not working

### ISSUE THREAD

**Issue by astbarc** [Angrycreative/bj-lazy-load#49]
I applied the filter 'bj_lazy_load_html' to an img element in the footer.php template.
I can see that in the source code the image contains the 'data-src' attribute but it loads when the page loads the instead of lazy loading when scroll down.

Any suggestions about how to fix this.

Thanks.

- [ ]

**Comment by jan-san** [comment]
Hi @astbarc 

A possible reason for this behavior is that the image or one of it's parent HTML elements was hidden via `display: none` - such images used to be loaded immediately in previous versions of the plugin, but this has been fixed in b360afdc7517e969f72e180a423bdfe4ad2bb971

Please reopen this ticket with a link to the site if the problem persists.
